# TAKE HOME LAB EXERCISE - 01

-----------

**(1).Create a 1D array with 10 values in it and then convert the 1D array to 2D array ?**

In [3]:
import numpy as np
x = np.array([10 ,7 , 4,  2,  5,  6,  0,5,  6,  3])
print(x)
np.reshape(x,(5,2))

[10  7  4  2  5  6  0  5  6  3]


array([[10,  7],
       [ 4,  2],
       [ 5,  6],
       [ 0,  5],
       [ 6,  3]])

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [18]:
np.set_printoptions(precision=3)
np.array([4.829342379832649])

array([4.829])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [19]:
np.set_printoptions(threshold=5) 
x = np.arange(15)
x

array([ 0,  1,  2, ..., 12, 13, 14])

---------------------

**(4). Take two arrays  `x` and `y` and Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
np.set_printoptions(threshold=1000) 
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). Consider the given array's and print the values which are common in both the arrays.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [26]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(x,y)

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [42]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
a = np.intersect1d(x,y)
np.delete(x,np.where(x == np.intersect1d(x,y)))

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [49]:
X = np.arange(9).reshape(3,3)
X[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [62]:
X = np.arange(9).reshape(3,3)
a = X.T
a[::-1].T

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [7]:
np.random.seed(10)
x = np.random.randint(20, size=10)
a = np.argsort(x,axis=0,kind='stable')
np.argsort(a,axis=0)

[ 9  4 15  0 17 16 17  8  9  0]


array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

--------------------

**(10). For the given numeric array print the rank array with same shape of numeric array.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [15]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(a)
a = np.ravel(x)
b = np.argsort(a)
np.argsort(b).reshape(2,5)

[ 9  4 15  0 17 16 17  8  9  0]


array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [73]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3]).reshape(3,1)
x_2d-y_1d

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------